In [1]:
import pandas as pd

In [2]:
ml_data = pd.read_csv("../../data_processed/combined_ml_data.csv")
ml_data.head()

,variety_id,variety_name,crop_name,trait_name,trait_type,location_id,town,lat,lon,country,...,humidity,rainfall,condition,month,year,tpe_name,tpe_description,stressors,yield,adoption_rate
0,1,Mucuvea(2015),sorghum,APHIDS_RESISTANCE,Desired,11,Maputo,-25.9686,32.5804,Mozambique,...,57.0,-0.1,broken clouds,December,2025,ARID,"Extremely dry areas with minimal rainfall, oft...","['DROUGHT', 'HEAT', 'STRIGA', 'SALINITY']",NaN,NaN
1,1,Mucuvea(2015),sorghum,APHIDS_RESISTANCE,Desired,11,Maputo,-25.9686,32.5804,Mozambique,...,59.0,0.1,broken clouds,November,2025,ARID,"Extremely dry areas with minimal rainfall, oft...","['DROUGHT', 'HEAT', 'STRIGA', 'SALINITY']",NaN,NaN
2,1,Mucuvea(2015),sorghum,APHIDS_RESISTANCE,Desired,11,Maputo,-25.9686,32.5804,Mozambique,...,57.0,-0.1,broken clouds,October,2025,ARID,"Extremely dry areas with minimal rainfall, oft...","['DROUGHT', 'HEAT', 'STRIGA', 'SALINITY']",NaN,NaN
3,1,Mucuvea(2015),sorghum,APHIDS_RESISTANCE,Desired,11,Maputo,-25.9686,32.5804,Mozambique,...,59.0,0.1,broken clouds,September,2025,ARID,"Extremely dry areas with minimal rainfall, oft...","['DROUGHT', 'HEAT', 'STRIGA', 'SALINITY']",NaN,NaN
4,1,Mucuvea(2015),sorghum,APHIDS_RESISTANCE,Desired,11,Maputo,-25.9686,32.5804,Mozambique,...,57.0,-0.1,broken clouds,August,2025,ARID,"Extremely dry areas with minimal rainfall, oft...","['DROUGHT', 'HEAT', 'STRIGA', 'SALINITY']",NaN,NaN

## Data review for cleaning

In [3]:
print(ml_data.isnull().sum())

variety_id              0
variety_name            0
crop_name               0
trait_name              0
trait_type              0
location_id             0
town                    0
lat                     0
lon                     0
country                 0
temperature             0
humidity                0
rainfall                0
condition               0
month                   0
year                    0
tpe_name                0
tpe_description         0
stressors               0
yield              144552
adoption_rate      144552
dtype: int64

In [4]:
ml_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144552 entries, 0 to 144551
Data columns (total 21 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   variety_id       144552 non-null  int64
 1   variety_name     144552 non-null  object
 2   crop_name        144552 non-null  object
 3   trait_name       144552 non-null  object
 4   trait_type       144552 non-null  object
 5   location_id      144552 non-null  int64
 6   town             144552 non-null  object
 7   lat              144552 non-null  float64
 8   lon              144552 non-null  float64
 9   country          144552 non-null  object
 10  temperature      144552 non-null  float64
 11  humidity         144552 non-null  float64
 12  rainfall         144552 non-null  float64
 13  condition        144552 non-null  object
 14  month            144552 non-null  object
 15  year             144552 non-null  int64
 16  tpe_name         144552 non-null  object
 17  tpe_description  144552 non-null  object
 18  stressors        144552 non-null  object
 19  yield            0 non-null       float64
 20  adoption_rate    0 non-null       float64
dtypes: float64(7), int64(3), object(11)
memory usage: 23.2+ MB

#### Drop null columns

In [5]:
# Drop the 'yield' and 'adoption_rate' columns
ml_data = ml_data.drop(columns=['yield', 'adoption_rate'])
ml_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144552 entries, 0 to 144551
Data columns (total 19 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   variety_id       144552 non-null  int64
 1   variety_name     144552 non-null  object
 2   crop_name        144552 non-null  object
 3   trait_name       144552 non-null  object
 4   trait_type       144552 non-null  object
 5   location_id      144552 non-null  int64
 6   town             144552 non-null  object
 7   lat              144552 non-null  float64
 8   lon              144552 non-null  float64
 9   country          144552 non-null  object
 10  temperature      144552 non-null  float64
 11  humidity         144552 non-null  float64
 12  rainfall         144552 non-null  float64
 13  condition        144552 non-null  object
 14  month            144552 non-null  object
 15  year             144552 non-null  int64
 16  tpe_name         144552 non-null  object
 17  tpe_description  144552 non-null  object
 18  stressors        144552 non-null  object
dtypes: float64(5), int64(3), object(11)
memory usage: 21.0+ MB

### ML Data preprocessing
* At this stage, we are preparing the data for machine learning by cleaning and transforming it into a format that algorithms can understand. This involves removing unnecessary columns, converting categorical data into numerical format using one-hot encoding, and scaling numerical features (like temperature and rainfall) to ensure they are on a similar scale. This preparation is crucial for accurate and effective machine learning analysis, which will help us recommend the best crop varieties for specific environments.

### Encoding categorical variables

* One-hot encoding is a technique used to convert categorical data (like names, labels, or categories) into a numerical format that machine learning algorithms can process. It creates new binary columns for each category in a variable, where a value of 1 indicates the presence of that category, and 0 indicates its absence. This prevents the algorithm from misinterpreting categorical data as having an ordinal relationship (e.g., assuming "2" is greater than "1").

In [6]:
ml_data_encoded = pd.get_dummies(ml_data, columns=['trait_name', 'tpe_name', 'condition', 'month', 'trait_type'])
ml_data_encoded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144552 entries, 0 to 144551
Columns: 142 entries, variety_id to trait_type_Positive
dtypes: bool(128), float64(5), int64(3), object(6)
memory usage: 33.1+ MB

In [7]:
# Step 3: Check for missing values and drop them if any
ml_data_encoded = ml_data_encoded.dropna()

### Scaling numerical features
* Scaling numerical features (like temperature and rainfall) to ensure they are on a similar scale **(normalizing independent variables or features of data) - data normalization**.
* Standardization or Feature scaling is the process of transforming the data we are working with into a standard scale. This translates to subtracting the mean and dividing by the standard deviation. In this way, regardless of the data set, we will always obtain a distribution with a mean of zero and a standard deviation of one, which could easily be proven.
* **standardscaler()** is used to standardize numerical features by removing the mean and scaling to unit variance.
* fit_transform: This method computes the mean and standard deviation of each feature (fit) and then scales the data so that each feature has a mean of 0 and a standard deviation of 1 (transform).
* The scaled values replace the original values in the ml_data_encoded DataFrame.

<h4>Why Scaling is Important: </h4>

* Algorithm Performance: Many machine learning algorithms (e.g., K-Means, SVM, Neural Networks) perform better when numerical features are on a similar scale. Scaling ensures that no single feature dominates the others due to its scale.
* Gradient Descent Convergence: Algorithms that use gradient descent (e.g., linear regression, logistic regression) converge faster when features are scaled.
* Distance Calculations: Algorithms that rely on distance calculations (e.g., K-Means, K-Nearest Neighbors) can be significantly affected by the scale of the features. Scaling ensures that each feature contributes equally to the distance calculation.

In [8]:
from sklearn.preprocessing import StandardScaler

numerical_features = ['temperature', 'humidity', 'rainfall', 'lat', 'lon']
scaler = StandardScaler()
ml_data_encoded[numerical_features] = scaler.fit_transform(ml_data_encoded[numerical_features])
ml_data_encoded.head()

,variety_id,variety_name,crop_name,location_id,town,lat,lon,country,temperature,humidity,...,month_July,month_June,month_March,month_May,month_November,month_October,month_September,trait_type_Desired,trait_type_Negative,trait_type_Positive
0,1,Mucuvea(2015),sorghum,11,Maputo,-2.727707,0.860637,Mozambique,-0.089199,0.415832,...,False,False,False,False,False,False,False,True,False,False
1,1,Mucuvea(2015),sorghum,11,Maputo,-2.727707,0.860637,Mozambique,0.333439,0.498563,...,False,False,False,False,True,False,False,True,False,False
2,1,Mucuvea(2015),sorghum,11,Maputo,-2.727707,0.860637,Mozambique,0.122120,0.415832,...,False,False,False,False,False,True,False,True,False,False
3,1,Mucuvea(2015),sorghum,11,Maputo,-2.727707,0.860637,Mozambique,-0.089199,0.498563,...,False,False,False,False,False,False,True,True,False,False
4,1,Mucuvea(2015),sorghum,11,Maputo,-2.727707,0.860637,Mozambique,0.333439,0.415832,...,False,False,False,False,False,False,False,True,False,False

### Clustering with K-Means
**Objective:**
Group crop varieties based on their traits and environmental conditions to identify patterns and similarities.

**Explanation:** K-Means Clustering: This algorithm groups data into k clusters by minimizing the variance within each cluster.</br>
Why Use K-Means?: It is simple, efficient, and effective for grouping data points based on feature similarity.

In [9]:
# Prepare features for clustering
X = ml_data_encoded.drop(columns=['variety_id', 'variety_name', 'crop_name', 'location_id', 'town', 'country', 'year'])
X = ml_data_encoded.select_dtypes(include=['float64', 'int64'])
X.head(2)

,variety_id,location_id,lat,lon,temperature,humidity,rainfall,year
0,1,11,-2.727707,0.860637,-0.089199,0.415832,-0.777001,2025
1,1,11,-2.727707,0.860637,0.333439,0.498563,-0.376919,2025

##### Applying K-Means Clustering
* We'll apply K-Means clustering to group the varieties based on their traits and environmental conditions.

In [10]:
from sklearn.cluster import KMeans

# Initialize K-Means with a chosen number of clusters
kmeans = KMeans(n_clusters=5, random_state=42)

# Fit the model to the data
kmeans.fit(X)

# Add cluster labels to the dataset
ml_data_encoded['cluster'] = kmeans.labels_

# Check the cluster assignments
print(ml_data_encoded[['variety_name', 'cluster']].drop_duplicates())

# n_clusters=5: We start with 5 clusters. You can adjust this number based on data and domain knowledge.
# random_state=42: Ensures reproducibility of the results.
# kmeans.fit(X): Fits the K-Means model to the data.
# ml_data_encoded['cluster']: Adds the cluster labels to the dataset.

        variety_name  cluster
0      Mucuvea(2015)        0
24     Mucuvea(2015)        2
456      otela(2015)        0
480      otela(2015)        2
912     Yeipa1(2019)        0
...              ...      ...
41064  ARAC216(2016)        1
41496   Seredo(1970)        3
41520   Seredo(1970)        1
71136  Grinkan(2007)        3
71160  Grinkan(2007)        1

[95 rows x 2 columns]

In [18]:
numeric_columns = ml_data_encoded.select_dtypes(include=['float64', 'int64']).columns
categorical_columns = ml_data_encoded.select_dtypes(include=['object']).columns

print("Numeric columns:", numeric_columns)
print("Categorical columns:", categorical_columns)

Numeric columns: Index(['variety_id', 'location_id', 'lat', 'lon', 'temperature', 'humidity',
       'rainfall', 'year'],
      dtype='object')
Categorical columns: Index(['variety_name', 'crop_name', 'town', 'country', 'tpe_description',
       'stressors'],
      dtype='object')

In [21]:
# Calculate mean for numeric columns by cluster
numeric_cluster_summary = ml_data_encoded[numeric_columns].groupby(ml_data_encoded['cluster']).mean()
numeric_cluster_summary

,variety_id,location_id,lat,lon,temperature,humidity,rainfall,year
cluster,,,,,,,,
0,9.264423,14.620192,-0.484942,0.595457,-0.307097,0.326260,0.356346,2024.5
1,40.568627,4.327887,0.657159,-0.907622,0.578055,-0.483935,-0.576960,2024.5
2,9.390938,4.884089,0.558131,-0.691732,0.327760,-0.338641,-0.382695,2024.5
3,41.138983,14.211017,-0.462555,0.641422,-0.456857,0.395850,0.449589,2024.5
4,25.808884,10.148760,-0.042760,0.058625,0.008664,-0.021070,-0.004281,2024.5

##### Combine Categorical Columns and numeric columns for Interpretation
* This provides a comprehensive summary of each cluster.

In [24]:
# Combine numeric and categorical summaries
cluster_full_summary = numeric_cluster_summary.copy()

for col in categorical_columns:
    unique_values = ml_data_encoded.groupby('cluster')[col].unique()
    cluster_full_summary[col] = unique_values

cluster_full_summary.head(2)

,variety_id,location_id,lat,lon,temperature,humidity,rainfall,year,variety_name,crop_name,town,country,tpe_description,stressors
cluster,,,,,,,,,,,,,,
0,9.264423,14.620192,-0.484942,0.595457,-0.307097,0.326260,0.356346,2024.5,"[Mucuvea(2015), otela(2015), Yeipa1(2019), Kap...",[sorghum],"[Maputo, Entebbe, Juba, Lomé, Niamey, Mombasa,...","[Mozambique, Uganda, South Sudan, Togo, Niger,...","[Extremely dry areas with minimal rainfall, of...","[['DROUGHT', 'HEAT', 'STRIGA', 'SALINITY']]"
1,40.568627,4.327887,0.657159,-0.907622,0.578055,-0.483935,-0.576960,2024.5,"[S-35(1986), Kolmonrouge(1993), Damougari(1998...",[sorghum],"[Tamale, Ouagadougou, Kumasi, Accra, Bobo-Diou...","[Ghana, Burkina Faso, Cameroon, Chad]","[Extremely dry areas with minimal rainfall, of...","[['DROUGHT', 'HEAT', 'STRIGA', 'SALINITY']]"

##### Save the Full Summary for Dashboard Use

In [27]:
cluster_full_summary.to_csv('../../data_processed/cluster_full_summary.csv')