In [1]:
import pandas as pd

In [2]:
cluster_full_summary = pd.read_csv("../../data_processed/cluster_full_summary.csv")
cluster_full_summary.head(2)

,cluster,variety_id,location_id,lat,lon,temperature,humidity,rainfall,year,variety_name,crop_name,town,country,tpe_description,stressors
0,0,9.264423,14.620192,-0.484942,0.595457,-0.307097,0.326260,0.356346,2024.5,['Mucuvea(2015)' 'otela(2015)' 'Yeipa1(2019)' ...,['sorghum'],['Maputo' 'Entebbe' 'Juba' 'Lomé' 'Niamey' 'Mo...,['Mozambique' 'Uganda' 'South Sudan' 'Togo' 'N...,"['Extremely dry areas with minimal rainfall, o...","[""['DROUGHT', 'HEAT', 'STRIGA', 'SALINITY']""]"
1,1,40.568627,4.327887,0.657159,-0.907622,0.578055,-0.483935,-0.576960,2024.5,['S-35(1986)' 'Kolmonrouge(1993)' 'Damougari(1...,['sorghum'],['Tamale' 'Ouagadougou' 'Kumasi' 'Accra' 'Bobo...,['Ghana' 'Burkina Faso' 'Cameroon' 'Chad'],"['Extremely dry areas with minimal rainfall, o...","[""['DROUGHT', 'HEAT', 'STRIGA', 'SALINITY']""]"

### Data cleaning and preparation
##### The variety_name, town, country, and stressors columns contain lists as strings (e.g., ["Mucuvea(2015)", "otela(2015)"]). We’ll convert these strings into proper Python lists for easier analysis.

In [3]:
import ast

# Convert string representations of lists to actual lists
for col in ['variety_name', 'town', 'country', 'stressors']:
    cluster_full_summary[col] = cluster_full_summary[col].apply(lambda x: ast.literal_eval(x) if pd.notna(x) else [])

cluster_full_summary.head()

,cluster,variety_id,location_id,lat,lon,temperature,humidity,rainfall,year,variety_name,crop_name,town,country,tpe_description,stressors
0,0,9.264423,14.620192,-0.484942,0.595457,-0.307097,0.326260,0.356346,2024.5,[Mucuvea(2015)otela(2015)Yeipa1(2019)Kapaala(1...,['sorghum'],[MaputoEntebbeJubaLoméNiameyMombasaKampalaArus...,[MozambiqueUgandaSouth SudanTogoNigerKenyaTanz...,"['Extremely dry areas with minimal rainfall, o...","[['DROUGHT', 'HEAT', 'STRIGA', 'SALINITY']]"
1,1,40.568627,4.327887,0.657159,-0.907622,0.578055,-0.483935,-0.576960,2024.5,[S-35(1986)Kolmonrouge(1993)Damougari(1998)Tia...,['sorghum'],[TamaleOuagadougouKumasiAccraBobo-DioulassoYao...,[GhanaBurkina FasoCameroonChad],"['Extremely dry areas with minimal rainfall, o...","[['DROUGHT', 'HEAT', 'STRIGA', 'SALINITY']]"
2,2,9.390938,4.884089,0.558131,-0.691732,0.327760,-0.338641,-0.382695,2024.5,[Mucuvea(2015)otela(2015)Yeipa1(2019)Kapaala(1...,['sorghum'],[N'DjamenaOuagadougouKumasiNairobiDoualaTamale...,[ChadBurkina FasoGhanaKenyaCameroon],"['Extremely dry areas with minimal rainfall, o...","[['DROUGHT', 'HEAT', 'STRIGA', 'SALINITY']]"
3,3,41.138983,14.211017,-0.462555,0.641422,-0.456857,0.395850,0.449589,2024.5,[Kolmonrouge(1993)Damougari(1998)Tiandougoucou...,['sorghum'],[EntebbeKampalaLoméArushaDar es SalaamMaputoJu...,[UgandaTogoTanzaniaMozambiqueSouth SudanNigerK...,"['Extremely dry areas with minimal rainfall, o...","[['DROUGHT', 'HEAT', 'STRIGA', 'SALINITY']]"
4,4,25.808884,10.148760,-0.042760,0.058625,0.008664,-0.021070,-0.004281,2024.5,[ABM(2019)SOUBATIMI(2019)PépéKalé(2019)CS-54(1...,['sorghum'],[MombasaNairobiMaputoN'DjamenaJubaNiameyDouala...,[KenyaMozambiqueChadSouth SudanNigerCameroonBu...,"['Extremely dry areas with minimal rainfall, o...","[['DROUGHT', 'HEAT', 'STRIGA', 'SALINITY']]"