In [1]:
import pandas as pd
import ast
import re

In [2]:
recommendation_table = pd.read_csv('../../data_processed/comprehensive_recommendation_table.csv')
recommendation_table

,cluster,Cluster,Numeric Summary,Varieties,Crops,Towns,Countries,TPE Descriptions,Stressors,Key Traits,Key TPEs,Key Conditions,Key Months
0,0,0,"{'lat': -0.37404625576550943, 'lon': 1.0396491...",['Mucuvea(2015)' 'otela(2015)' 'Yeipa1(2019)' ...,['sorghum'],['Entebbe' 'Nairobi' 'Kampala' 'Arusha' 'Dar e...,['Uganda' 'Kenya' 'Tanzania'],"['Extremely dry areas with minimal rainfall, o...","[""['DROUGHT', 'HEAT', 'STRIGA', 'SALINITY']""]",{'trait_name_APHIDS_RESISTANCE': 0.00630914826...,{'tpe_name_ARID': 1.0},"{'condition_broken clouds': 0.0, 'condition_cl...","{'month_April': 0.08333333333333333, 'month_Au..."
1,1,1,"{'lat': 1.0695926482126925, 'lon': -1.16717511...",['Mucuvea(2015)' 'otela(2015)' 'Yeipa1(2019)' ...,['sorghum'],['Ouagadougou' 'Niamey' 'Bobo-Dioulasso'],['Burkina Faso' 'Niger'],"['Extremely dry areas with minimal rainfall, o...","[""['DROUGHT', 'HEAT', 'STRIGA', 'SALINITY']""]",{'trait_name_APHIDS_RESISTANCE': 0.00630914826...,{'tpe_name_ARID': 1.0},"{'condition_broken clouds': 0.0, 'condition_cl...","{'month_April': 0.08333333333333333, 'month_Au..."
2,2,2,"{'lat': 0.47815219598739006, 'lon': -0.9929499...",['Mucuvea(2015)' 'otela(2015)' 'Yeipa1(2019)' ...,['sorghum'],['Kumasi' 'Lomé' 'Douala' 'Tamale' 'Accra'],['Ghana' 'Togo' 'Cameroon'],"['Extremely dry areas with minimal rainfall, o...","[""['DROUGHT', 'HEAT', 'STRIGA', 'SALINITY']""]",{'trait_name_APHIDS_RESISTANCE': 0.00630914826...,{'tpe_name_ARID': 1.0},"{'condition_broken clouds': 0.4, 'condition_cl...","{'month_April': 0.08333333333333333, 'month_Au..."
3,3,3,"{'lat': -1.777248473703296, 'lon': 1.020039697...",['Mucuvea(2015)' 'otela(2015)' 'Yeipa1(2019)' ...,['sorghum'],['Maputo' 'Mombasa' 'Chimoio'],['Mozambique' 'Kenya'],"['Extremely dry areas with minimal rainfall, o...","[""['DROUGHT', 'HEAT', 'STRIGA', 'SALINITY']""]",{'trait_name_APHIDS_RESISTANCE': 0.00630914826...,{'tpe_name_ARID': 1.0},{'condition_broken clouds': 0.6666666666666666...,"{'month_April': 0.08333333333333333, 'month_Au..."
4,4,4,"{'lat': 0.5341459251208026, 'lon': 0.069303404...",['Mucuvea(2015)' 'otela(2015)' 'Yeipa1(2019)' ...,['sorghum'],"[""N'Djamena"" 'Juba' 'Yaoundé']",['Chad' 'South Sudan' 'Cameroon'],"['Extremely dry areas with minimal rainfall, o...","[""['DROUGHT', 'HEAT', 'STRIGA', 'SALINITY']""]",{'trait_name_APHIDS_RESISTANCE': 0.00630914826...,{'tpe_name_ARID': 1.0},{'condition_broken clouds': 0.3333333333333333...,"{'month_April': 0.08333333333333333, 'month_Au..."

#### Parse and clean Data
* This is because the csv file columns have values in concatenated strings in lists or dictionaries.

In [10]:
import ast
import re

def parse_list(column_value):
    """Parse a string representation of a list into an actual list."""
    try:
        return ast.literal_eval(column_value)
    except (ValueError, SyntaxError):
        return []

def parse_dict(column_value):
    """Parse a string representation of a dictionary into an actual dictionary."""
    try:
        return ast.literal_eval(column_value)
    except (ValueError, SyntaxError):
        return {}

def split_concatenated_string(concatenated_string):
    """Split a concatenated string into a list of items based on capital letters."""
    if not concatenated_string:
        return []
    items = re.findall(r'[A-Z][a-zA-Z0-9\(\)]+', str(concatenated_string))
    return items

# Apply parsing functions to all relevant columns
recommendation_table['Varieties'] = recommendation_table['Varieties'].apply(
    lambda x: split_concatenated_string(str(x).strip("[]'"))
)
recommendation_table['Crops'] = recommendation_table['Crops'].apply(
    lambda x: split_concatenated_string(str(x).strip("[]'"))
)
recommendation_table['Towns'] = recommendation_table['Towns'].apply(
    lambda x: split_concatenated_string(str(x).strip("[]'"))
)
recommendation_table['Countries'] = recommendation_table['Countries'].apply(
    lambda x: split_concatenated_string(str(x).strip("[]'"))
)
recommendation_table['TPE Descriptions'] = recommendation_table['TPE Descriptions'].apply(
    lambda x: split_concatenated_string(str(x).strip("[]'"))
)
recommendation_table['Stressors'] = recommendation_table['Stressors'].apply(
    lambda x: split_concatenated_string(str(x).strip("[]'"))
)
recommendation_table['Key Traits'] = recommendation_table['Key Traits'].apply(parse_dict)
recommendation_table['Key TPEs'] = recommendation_table['Key TPEs'].apply(parse_dict)
recommendation_table['Key Conditions'] = recommendation_table['Key Conditions'].apply(parse_dict)
recommendation_table['Key Months'] = recommendation_table['Key Months'].apply(parse_dict)
recommendation_table['Numeric Summary'] = recommendation_table['Numeric Summary'].apply(parse_dict)

recommendation_table.head()

,cluster,Cluster,Numeric Summary,Varieties,Crops,Towns,Countries,TPE Descriptions,Stressors,Key Traits,Key TPEs,Key Conditions,Key Months
0,0,0,{},"[Mucuvea(2015), Yeipa1(2019), Kapaala(1996), D...",[],"[Entebbe, Nairobi, Kampala, Arusha, Dar, Salaam]","[Uganda, Kenya, Tanzania]",[Extremely],"[DROUGHT, HEAT, STRIGA, SALINITY]",{},{},{},{}
1,1,1,{},"[Mucuvea(2015), Yeipa1(2019), Kapaala(1996), D...",[],"[Ouagadougou, Niamey, Bobo, Dioulasso]","[Burkina, Faso, Niger]",[Extremely],"[DROUGHT, HEAT, STRIGA, SALINITY]",{},{},{},{}
2,2,2,{},"[Mucuvea(2015), Yeipa1(2019), Kapaala(1996), D...",[],"[Kumasi, Lom, Douala, Tamale, Accra]","[Ghana, Togo, Cameroon]",[Extremely],"[DROUGHT, HEAT, STRIGA, SALINITY]",{},{},{},{}
3,3,3,{},"[Mucuvea(2015), Yeipa1(2019), Kapaala(1996), D...",[],"[Maputo, Mombasa, Chimoio]","[Mozambique, Kenya]",[Extremely],"[DROUGHT, HEAT, STRIGA, SALINITY]",{},{},{},{}
4,4,4,{},"[Mucuvea(2015), Yeipa1(2019), Kapaala(1996), D...",[],"[Djamena, Juba, Yaound]","[Chad, South, Sudan, Cameroon]",[Extremely],"[DROUGHT, HEAT, STRIGA, SALINITY]",{},{},{},{}

* The code above defines helper functions to parse and clean the data.
- The functions are applied to all relevant columns to convert concatenated strings into lists or dictionaries.

#### Extracting basic insights to confirm if it was parsed well for analysis
* The code defines helper functions to parse and clean the data.
* It applies these functions to all relevant columns to convert concatenated strings into lists or dictionaries.

In [11]:
# Number of clusters
num_clusters = recommendation_table['Cluster'].nunique()
print(f"\nNumber of clusters: {num_clusters}")

# Unique countries
unique_countries = set()
for countries in recommendation_table['Countries']:
    unique_countries.update(countries)
print(f"Unique countries: {unique_countries}")

# Unique varieties
unique_varieties = set()
for varieties in recommendation_table['Varieties']:
    unique_varieties.update(varieties)
print(f"Number of unique varieties: {len(unique_varieties)}")

Number of clusters: 5
Unique countries: {'Faso', 'Chad', 'Sudan', 'Kenya', 'South', 'Burkina', 'Niger', 'Tanzania', 'Togo', 'Mozambique', 'Uganda', 'Cameroon', 'Ghana'}
Number of unique varieties: 48

In [13]:
from collections import defaultdict

# Create a dictionary to map each variety to its countries
variety_to_countries = defaultdict(set)

for index, row in recommendation_table.iterrows():
    varieties = row['Varieties']
    countries = row['Countries']
    for variety in varieties:
        for country in countries:
            variety_to_countries[variety].add(country)

# Display the mapping for a few varieties
print("Variety to Countries Mapping (sample):")
for variety, countries in list(variety_to_countries.items())[:5]:
    print(f"{variety}: {countries}")

Variety to Countries Mapping (sample):
Mucuvea(2015): {'Faso', 'Chad', 'Sudan', 'Kenya', 'South', 'Burkina', 'Niger', 'Tanzania', 'Togo', 'Mozambique', 'Uganda', 'Cameroon', 'Ghana'}
Yeipa1(2019): {'Faso', 'Chad', 'Sudan', 'Kenya', 'South', 'Burkina', 'Niger', 'Tanzania', 'Togo', 'Mozambique', 'Uganda', 'Cameroon', 'Ghana'}
Kapaala(1996): {'Faso', 'Chad', 'Sudan', 'Kenya', 'South', 'Burkina', 'Niger', 'Tanzania', 'Togo', 'Mozambique', 'Uganda', 'Cameroon', 'Ghana'}
Dorado(1996): {'Faso', 'Chad', 'Sudan', 'Kenya', 'South', 'Burkina', 'Niger', 'Tanzania', 'Togo', 'Mozambique', 'Uganda', 'Cameroon', 'Ghana'}
AtokpleChi(2022): {'Faso', 'Chad', 'Sudan', 'Kenya', 'South', 'Burkina', 'Niger', 'Tanzania', 'Togo', 'Mozambique', 'Uganda', 'Cameroon', 'Ghana'}

#### Refering on the initial csv file, coz i have noticed varieties should reflect their own country

In [16]:
original_data = pd.read_csv('../../data_processed/combined_ml_data.csv')
original_data.head()

,variety_id,variety_name,crop_name,trait_name,trait_type,location_id,town,lat,lon,country,...,humidity,rainfall,condition,month,year,tpe_name,tpe_description,stressors,yield,adoption_rate
0,1,Mucuvea(2015),sorghum,APHIDS_RESISTANCE,Desired,11,Maputo,-25.9686,32.5804,Mozambique,...,57.0,-0.1,broken clouds,December,2025,ARID,"Extremely dry areas with minimal rainfall, oft...","['DROUGHT', 'HEAT', 'STRIGA', 'SALINITY']",NaN,NaN
1,1,Mucuvea(2015),sorghum,APHIDS_RESISTANCE,Desired,11,Maputo,-25.9686,32.5804,Mozambique,...,59.0,0.1,broken clouds,November,2025,ARID,"Extremely dry areas with minimal rainfall, oft...","['DROUGHT', 'HEAT', 'STRIGA', 'SALINITY']",NaN,NaN
2,1,Mucuvea(2015),sorghum,APHIDS_RESISTANCE,Desired,11,Maputo,-25.9686,32.5804,Mozambique,...,57.0,-0.1,broken clouds,October,2025,ARID,"Extremely dry areas with minimal rainfall, oft...","['DROUGHT', 'HEAT', 'STRIGA', 'SALINITY']",NaN,NaN
3,1,Mucuvea(2015),sorghum,APHIDS_RESISTANCE,Desired,11,Maputo,-25.9686,32.5804,Mozambique,...,59.0,0.1,broken clouds,September,2025,ARID,"Extremely dry areas with minimal rainfall, oft...","['DROUGHT', 'HEAT', 'STRIGA', 'SALINITY']",NaN,NaN
4,1,Mucuvea(2015),sorghum,APHIDS_RESISTANCE,Desired,11,Maputo,-25.9686,32.5804,Mozambique,...,57.0,-0.1,broken clouds,August,2025,ARID,"Extremely dry areas with minimal rainfall, oft...","['DROUGHT', 'HEAT', 'STRIGA', 'SALINITY']",NaN,NaN

#### Analyze Clusters by Country
- This function filters clusters that include a specific country and displays the varieties and other relevant information.
- It helps you understand which varieties are recommended for specific countries.

In [12]:
def analyze_clusters_by_country(country_of_interest):
    clusters_for_country = recommendation_table[
        recommendation_table['Countries'].apply(lambda x: country_of_interest in x)
    ]

    if clusters_for_country.empty:
        print(f"\nNo clusters found for {country_of_interest}.")
    else:
        print(f"\nClusters for {country_of_interest}:")
        for index, row in clusters_for_country.iterrows():
            print(f"\nCluster {row['Cluster']}:")
            print(f"Varieties: {row['Varieties']}")
            print(f"TPE Descriptions: {row['TPE Descriptions']}")
            print(f"Stressors: {row['Stressors']}")

# Example: Analyze clusters for Kenya
analyze_clusters_by_country('Kenya')

Clusters for Kenya:

Cluster 0:
Varieties: ['Mucuvea(2015)', 'Yeipa1(2019)', 'Kapaala(1996)', 'Dorado(1996)', 'AtokpleChi(2022)', 'AdSARGHUM1(2022)', 'AdSARGHUM2(2022)', 'AdSARGHUM3(2022)', 'Gadam(1994)', 'KariMtama1(2000)', 'Kamani(2019)', 'SESO1(2011)', 'NAROSORG1(2017)', 'NAROSORG4(2017)', 'SORVATO9(2019)', 'ABM(2019)', 'SOUBATIMI(2019)', 'Kal', 'CS', 'Soubatimi(2015)', 'Zouaye(2004)', 'Tocole(2015)', 'Maita', 'Mapupulo(2015)', 'Seso3(2018)', 'SESO3(2011)', 'IRAT', 'IRAT204(1980)', 'Kolmonrouge(1993)', 'Damougari(1998)', 'Tiandougoucoura(2010)', 'Sila(2016)', 'Fadda(2010)', 'Mota', 'Maradi(1994)', 'K3R(1995)', 'Tegemeo(1983)', 'TARISOR1(2021)', 'TARISOR2(2021)', 'Macia(1999)', 'Wahi(2002)', 'Pablo(2011)', 'NAROSORG2(2017)', 'Macia(2012)', 'AGRAC116(2016)', 'ARAC216(2016)', 'Seredo(1970)', 'Grinkan(2007)']
TPE Descriptions: ['Extremely']
Stressors: ['DROUGHT', 'HEAT', 'STRIGA', 'SALINITY']

Cluster 3:
Varieties: ['Mucuvea(2015)', 'Yeipa1(2019)', 'Kapaala(1996)', 'Dorado(1996)', 'AtokpleChi(2022)', 'AdSARGHUM1(2022)', 'AdSARGHUM2(2022)', 'AdSARGHUM3(2022)', 'Gadam(1994)', 'KariMtama1(2000)', 'Kamani(2019)', 'SESO1(2011)', 'NAROSORG1(2017)', 'NAROSORG4(2017)', 'SORVATO9(2019)', 'ABM(2019)', 'SOUBATIMI(2019)', 'Kal', 'CS', 'Soubatimi(2015)', 'Zouaye(2004)', 'Tocole(2015)', 'Maita', 'Mapupulo(2015)', 'Seso3(2018)', 'SESO3(2011)', 'IRAT', 'IRAT204(1980)', 'Kolmonrouge(1993)', 'Damougari(1998)', 'Tiandougoucoura(2010)', 'Sila(2016)', 'Fadda(2010)', 'Mota', 'Maradi(1994)', 'K3R(1995)', 'Tegemeo(1983)', 'TARISOR1(2021)', 'TARISOR2(2021)', 'Macia(1999)', 'Wahi(2002)', 'Pablo(2011)', 'NAROSORG2(2017)', 'Macia(2012)', 'AGRAC116(2016)', 'ARAC216(2016)', 'Seredo(1970)', 'Grinkan(2007)']
TPE Descriptions: ['Extremely']
Stressors: ['DROUGHT', 'HEAT', 'STRIGA', 'SALINITY']

### Extract and interpret cluster information

#### Analyze Each Cluster
* Loop iterates through each row in the recommendation table and prints the characteristics of each cluster.
* Helps you understand the traits, environmental conditions, and locations associated with each cluster.

In [26]:
# Loop through each cluster to display its characteristics
for index, row in recommendation_table.iterrows():
    cluster = row['Cluster']
    print(f"\nCluster {cluster} Analysis:")

    # Display numeric summary
    print("\nNumeric Summary:")
    print(row['Numeric Summary'])

    # Display varieties
    print("\nVarieties:")
    print(row['Varieties'])

    # Display crops
    print("\nCrops:")
    print(row['Crops'])

    # Display towns
    print("\nTowns:")
    print(row['Towns'])

    # Display countries
    print("\nCountries:")
    print(row['Countries'])

    # Display TPE descriptions
    print("\nTPE Descriptions:")
    print(row['TPE Descriptions'])

    # Display stressors
    print("\nStressors:")
    print(row['Stressors'])

    # Display key traits
    print("\nKey Traits:")
    print(row['Key Traits'])

    # Display key TPEs
    print("\nKey TPEs:")
    print(row['Key TPEs'])

    # Display key conditions
    print("\nKey Conditions:")
    print(row['Key Conditions'])

    # Display key months
    print("\nKey Months:")
    print(row['Key Months'])

Cluster 0 Analysis:

Numeric Summary:
{'lat': -0.37404625576550943, 'lon': 1.039649168582761, 'temperature': -1.4065595706644751, 'humidity': 1.0611335039980898, 'rainfall': 1.5314718574383968}

Varieties:
['Mucuvea(2015)otela(2015)Yeipa1(2019)Kapaala(1996)Dorado(1996)AtokpleChi(2022)AdSARGHUM1(2022)AdSARGHUM2(2022)AdSARGHUM3(2022)Gadam(1994)KariMtama1(2000)Kamani(2019)SESO1(2011)NAROSORG1(2017)NAROSORG4(2017)SORVATO9(2019)ABM(2019)SOUBATIMI(2019)PépéKalé(2019)CS-54(1992)S-35(1965)Soubatimi(2015)Zouaye(2004)Tocole(2015)Maita-1(2015)Mapupulo(2015)Seso3(2018)SESO3(2011)IRAT-204(1994)IRAT204(1980)S-35(1986)Kolmonrouge(1993)Damougari(1998)Tiandougoucoura(2010)Sila(2016)Fadda(2010)Mota-Maradi(1994)K3R(1995)Tegemeo(1983)TARISOR1(2021)TARISOR2(2021)Macia(1999)Wahi(2002)Pablo(2011)NAROSORG2(2017)Macia(2012)AGRAC116(2016)ARAC216(2016)Seredo(1970)Grinkan(2007)']

Crops:
['sorghum']

Towns:
['EntebbeNairobiKampalaArushaDaresSalaam']

Countries:
['UgandaKenyaTanzania']

TPE Descriptions:
['Extremely dry areas with minimal rainfall, often less than 400 mm annually']

Stressors:
["['DROUGHT', 'HEAT', 'STRIGA', 'SALINITY']"]

Key Traits:
{'trait_name_APHIDS_RESISTANCE': 0.006309148264984227, 'trait_name_APPEALING_GRAIN_COLOR': 0.0031545741324921135, 'trait_name_BIRD_DAMAGE_RESISTANCE': 0.056782334384858045, 'trait_name_COMPACT_PANICLE': 0.00946372239747634, 'trait_name_DOES_NOT_PERFORM_WELL_IN_HEAVY/CLAY_SOIL_ENVIRONMENT.': 0.0031545741324921135, 'trait_name_DROUGHT_SUSCEPTIBLE': 0.0031545741324921135, 'trait_name_DROUGHT_TOLERANT': 0.056782334384858045, 'trait_name_DUAL-PURPOSE_VARIETY': 0.0031545741324921135, 'trait_name_DUAL_PURPOSE_VARIETY': 0.015772870662460567, 'trait_name_DUAL_PURPOSE_VARIETY.': 0.0031545741324921135, 'trait_name_EARLINESS': 0.015772870662460567, 'trait_name_EARLY_MATURITY': 0.06624605678233439, 'trait_name_EXCESSIVE_TILLERING': 0.0031545741324921135, 'trait_name_GOOD_FOR_BREWING': 0.0031545741324921135, 'trait_name_GOOD_FOR_FOOD': 0.0473186119873817, 'trait_name_GOOD_FOR_FOOD.': 0.0031545741324921135, 'trait_name_GOOD_MALTING_QUALITIES': 0.05993690851735016, 'trait_name_GOOD_MILLING_QUALITY': 0.0031545741324921135, 'trait_name_GRAIN_MOLD_SUSCEPTIBILITY': 0.0031545741324921135, 'trait_name_HIGH_GRAIN_QUALITY': 0.012618296529968454, 'trait_name_HIGH_GRAIN_YIELD': 0.08517350157728706, 'trait_name_HIGH_RATE_OF_ROTTING_IN_RAINFALL_AREAS': 0.0031545741324921135, 'trait_name_HIGH_TANNIN_LEVELS': 0.0031545741324921135, 'trait_name_HIGH_THRESHABILITY': 0.0031545741324921135, 'trait_name_HIGH_YIELDING': 0.0031545741324921135, 'trait_name_IMPROVE_GRAIN_COLOUR': 0.012618296529968454, 'trait_name_IMPROVE_GRAIN_QUALITY': 0.006309148264984227, 'trait_name_IMPROVE_GRAIN_SIZE': 0.0031545741324921135, 'trait_name_IMPROVE_GRAIN_YIELD': 0.0031545741324921135, 'trait_name_IMPROVE_ON_YIELD': 0.0031545741324921135, 'trait_name_IMPROVE_PALATABILITY_AND_GRAIN_QUALITY': 0.0031545741324921135, 'trait_name_IMPROVE_RESISTANCE_TO_STRIGA': 0.0031545741324921135, 'trait_name_IMPROVE_RESISTANCE_TO_WATER_LOGGING': 0.0031545741324921135, 'trait_name_IMPROVE_STABILITY': 0.0031545741324921135, 'trait_name_IMPROVE_STOVER_DIGESTIBILITY': 0.006309148264984227, 'trait_name_IMPROVE_STOVE_DIGESTIBILITY': 0.0031545741324921135, 'trait_name_IMPROVE_TOLERANCE_TO_HUMID_CONDITIONS': 0.006309148264984227, 'trait_name_IMPROVE_TO_SEMI-LOOSE_PANICLE': 0.00946372239747634, 'trait_name_INSECT_RESISTANT': 0.0031545741324921135, 'trait_name_INSTABILITY': 0.0031545741324921135, 'trait_name_LARGE_GRAIN_SIZE': 0.0031545741324921135, 'trait_name_LARGE_HEAD_SIZE': 0.0031545741324921135, 'trait_name_LARGE_SEED_SIZE': 0.006309148264984227, 'trait_name_LATE_MATURITY': 0.012618296529968454, 'trait_name_LODGING_RESISTANT': 0.0031545741324921135, 'trait_name_LOWER_LEVEL_OF_TANNINS': 0.0031545741324921135, 'trait_name_LOW_PALATABILITY': 0.0031545741324921135, 'trait_name_LOW_STOVER_DIGESTIBILITY': 0.006309148264984227, 'trait_name_LOW_YIELD': 0.0031545741324921135, 'trait_name_MEDIUM_MATURING': 0.015772870662460567, 'trait_name_MEDIUM_MATURITY': 0.0031545741324921135, 'trait_name_MICRONUTRIENT_RICH': 0.0031545741324921135, 'trait_name_MOLD_RESISTANCE': 0.01892744479495268, 'trait_name_NARROW_ADAPTATION': 0.0031545741324921135, 'trait_name_OPEN_PANICLE': 0.015772870662460567, 'trait_name_POOR_STORABILITY': 0.0031545741324921135, 'trait_name_PRONE_TO_HEAT_STRESS': 0.0031545741324921135, 'trait_name_REDUCE_PLANT_HEIGHT': 0.0031545741324921135, 'trait_name_RESISTANCE_TO_ANTHRACNOSE': 0.00946372239747634, 'trait_name_RESISTANCE_TO_CHARCOAL_ROT': 0.006309148264984227, 'trait_name_RESISTANCE_TO_COVERED_KERNEL_SMUT': 0.006309148264984227, 'trait_name_RESISTANCE_TO_ELONGATED_SMUT': 0.006309148264984227, 'trait_name_RESISTANCE_TO_SOOTY_BLOTCH': 0.0031545741324921135, 'trait_name_RESISTANCE_TO_SORGHUM_MIDGE': 0.006309148264984227, 'trait_name_RESISTANCE_TO_STRIGA': 0.0031545741324921135, 'trait_name_RESISTANCE_TO_WATER_LOGGING': 0.0031545741324921135, 'trait_name_RESISTANT_TO_BIRD_DAMAGE': 0.0031545741324921135, 'trait_name_RESISTANT_TO_CHARCOAL_ROT': 0.0031545741324921135, 'trait_name_RESISTANT_TO_CHARCOAL_ROT.': 0.0031545741324921135, 'trait_name_RESISTANT_TO_CHARCOL_ROT': 0.0031545741324921135, 'trait_name_RESISTANT_TO_COVERED_KERNEL_SMUT': 0.006309148264984227, 'trait_name_RESISTANT_TO_GRAIN_MOLD': 0.012618296529968454, 'trait_name_RESISTANT_TO_LODGING': 0.00946372239747634, 'trait_name_RESISTANT_TO_STRIGA': 0.031545741324921134, 'trait_name_SHORT_STATURE': 0.0031545741324921135, 'trait_name_SMALL_GRAIN_SIZE': 0.0031545741324921135, 'trait_name_STAY_GREEN': 0.022082018927444796, 'trait_name_STRIGA_RESISTANCE': 0.006309148264984227, 'trait_name_STRIGA_TOLERANCE': 0.0031545741324921135, 'trait_name_SUSCEPTIBILITY_TO_WATER_LOGGING': 0.0031545741324921135, 'trait_name_SUSCEPTIBLE_TO_ANTHRACNOSE': 0.00946372239747634, 'trait_name_SUSCEPTIBLE_TO_BIRD_DAMAGE': 0.04416403785488959, 'trait_name_SUSCEPTIBLE_TO_CHARCOAL_ROT': 0.0031545741324921135, 'trait_name_SUSCEPTIBLE_TO_COVERED_KERNEL_SMUT': 0.006309148264984227, 'trait_name_SUSCEPTIBLE_TO_ELONGATED_SMUT': 0.0031545741324921135, 'trait_name_SUSCEPTIBLE_TO_ERGOT': 0.0031545741324921135, 'trait_name_SUSCEPTIBLE_TO_GRAIN_MOLD': 0.00946372239747634, 'trait_name_SUSCEPTIBLE_TO_MIDGE': 0.0031545741324921135, 'trait_name_SUSCEPTIBLE_TO_SEED_ABORTION': 0.0031545741324921135, 'trait_name_SUSCEPTIBLE_TO_SHOOT_FLY_DAMAGE_.': 0.0031545741324921135, 'trait_name_SUSCEPTIBLE_TO_SOOTY_BLOTCH': 0.0031545741324921135, 'trait_name_SUSCEPTIBLE_TO_SORGHUM_MIDGE': 0.012618296529968454, 'trait_name_SUSCEPTIBLE_TO_STRIGA': 0.012618296529968454, 'trait_name_SUSCEPTIBLE_TO_WATER_LOGGING': 0.00946372239747634, 'trait_name_TALL_PLANT_HEIGHT': 0.0031545741324921135, 'trait_name_TOLERANCE_TO_HEAT_STRESS': 0.0031545741324921135, 'trait_name_TOLERANCE_TO_HIGH_MOISTURE': 0.0031545741324921135, 'trait_name_TOLERANCE_TO_SORGHUM_MIDGE': 0.006309148264984227, 'trait_name_TOLERANT_TO_CHARCOAL_ROT': 0.0031545741324921135, 'trait_name_TOLERANT_TO_ELONGATED_SMUT': 0.0031545741324921135, 'trait_name_TOLERANT_TO_STRIGA': 0.0031545741324921135, 'trait_name_TOLERANT_TO_WATER_LOGGING': 0.0031545741324921135, 'trait_name_UNDESIRABLE_GRAIN_COLOUR': 0.00946372239747634, 'trait_name_UNDESIRABLE_RED_COLOR': 0.0031545741324921135, 'trait_name_WIDEN_ADAPTATION': 0.0031545741324921135, 'trait_name_WIDE_ADAPTATION': 0.00946372239747634, 'trait_type_Desired': 0.29652996845425866, 'trait_type_Negative': 0.22082018927444794, 'trait_type_Positive': 0.48264984227129337}

Key TPEs:
{'tpe_name_ARID': 1.0}

Key Conditions:
{'condition_broken clouds': 0.0, 'condition_clear sky': 0.0, 'condition_light rain': 0.6, 'condition_moderate rain': 0.4, 'condition_overcast clouds': 0.0, 'condition_scattered clouds': 0.0}

Key Months:
{'month_April': 0.08333333333333333, 'month_August': 0.08333333333333333, 'month_December': 0.08333333333333333, 'month_February': 0.08333333333333333, 'month_January': 0.08333333333333333, 'month_July': 0.08333333333333333, 'month_June': 0.08333333333333333, 'month_March': 0.08333333333333333, 'month_May': 0.08333333333333333, 'month_November': 0.08333333333333333, 'month_October': 0.08333333333333333, 'month_September': 0.08333333333333333}

Cluster 1 Analysis:

Numeric Summary:
{'lat': 1.0695926482126925, 'lon': -1.167175117763774, 'temperature': 0.9096343582681929, 'humidity': -1.3077298414748717, 'rainfall': -0.5769603862754306}

Varieties:
['Mucuvea(2015)otela(2015)Yeipa1(2019)Kapaala(1996)Dorado(1996)AtokpleChi(2022)AdSARGHUM1(2022)AdSARGHUM2(2022)AdSARGHUM3(2022)Gadam(1994)KariMtama1(2000)Kamani(2019)SESO1(2011)NAROSORG1(2017)NAROSORG4(2017)SORVATO9(2019)ABM(2019)SOUBATIMI(2019)PépéKalé(2019)CS-54(1992)S-35(1965)Soubatimi(2015)Zouaye(2004)Tocole(2015)Maita-1(2015)Mapupulo(2015)Seso3(2018)SESO3(2011)IRAT-204(1994)IRAT204(1980)S-35(1986)Kolmonrouge(1993)Damougari(1998)Tiandougoucoura(2010)Sila(2016)Fadda(2010)Mota-Maradi(1994)K3R(1995)Tegemeo(1983)TARISOR1(2021)TARISOR2(2021)Macia(1999)Wahi(2002)Pablo(2011)NAROSORG2(2017)Macia(2012)AGRAC116(2016)ARAC216(2016)Seredo(1970)Grinkan(2007)']

Crops:
['sorghum']

Towns:
['OuagadougouNiameyBobo-Dioulasso']

Countries:
['BurkinaFasoNiger']

TPE Descriptions:
['Extremely dry areas with minimal rainfall, often less than 400 mm annually']

Stressors:
["['DROUGHT', 'HEAT', 'STRIGA', 'SALINITY']"]

Key Traits:
{'trait_name_APHIDS_RESISTANCE': 0.006309148264984227, 'trait_name_APPEALING_GRAIN_COLOR': 0.0031545741324921135, 'trait_name_BIRD_DAMAGE_RESISTANCE': 0.056782334384858045, 'trait_name_COMPACT_PANICLE': 0.00946372239747634, 'trait_name_DOES_NOT_PERFORM_WELL_IN_HEAVY/CLAY_SOIL_ENVIRONMENT.': 0.0031545741324921135, 'trait_name_DROUGHT_SUSCEPTIBLE': 0.0031545741324921135, 'trait_name_DROUGHT_TOLERANT': 0.056782334384858045, 'trait_name_DUAL-PURPOSE_VARIETY': 0.0031545741324921135, 'trait_name_DUAL_PURPOSE_VARIETY': 0.015772870662460567, 'trait_name_DUAL_PURPOSE_VARIETY.': 0.0031545741324921135, 'trait_name_EARLINESS': 0.015772870662460567, 'trait_name_EARLY_MATURITY': 0.06624605678233439, 'trait_name_EXCESSIVE_TILLERING': 0.0031545741324921135, 'trait_name_GOOD_FOR_BREWING': 0.0031545741324921135, 'trait_name_GOOD_FOR_FOOD': 0.0473186119873817, 'trait_name_GOOD_FOR_FOOD.': 0.0031545741324921135, 'trait_name_GOOD_MALTING_QUALITIES': 0.05993690851735016, 'trait_name_GOOD_MILLING_QUALITY': 0.0031545741324921135, 'trait_name_GRAIN_MOLD_SUSCEPTIBILITY': 0.0031545741324921135, 'trait_name_HIGH_GRAIN_QUALITY': 0.012618296529968454, 'trait_name_HIGH_GRAIN_YIELD': 0.08517350157728706, 'trait_name_HIGH_RATE_OF_ROTTING_IN_RAINFALL_AREAS': 0.0031545741324921135, 'trait_name_HIGH_TANNIN_LEVELS': 0.0031545741324921135, 'trait_name_HIGH_THRESHABILITY': 0.0031545741324921135, 'trait_name_HIGH_YIELDING': 0.0031545741324921135, 'trait_name_IMPROVE_GRAIN_COLOUR': 0.012618296529968454, 'trait_name_IMPROVE_GRAIN_QUALITY': 0.006309148264984227, 'trait_name_IMPROVE_GRAIN_SIZE': 0.0031545741324921135, 'trait_name_IMPROVE_GRAIN_YIELD': 0.0031545741324921135, 'trait_name_IMPROVE_ON_YIELD': 0.0031545741324921135, 'trait_name_IMPROVE_PALATABILITY_AND_GRAIN_QUALITY': 0.0031545741324921135, 'trait_name_IMPROVE_RESISTANCE_TO_STRIGA': 0.0031545741324921135, 'trait_name_IMPROVE_RESISTANCE_TO_WATER_LOGGING': 0.0031545741324921135, 'trait_name_IMPROVE_STABILITY': 0.0031545741324921135, 'trait_name_IMPROVE_STOVER_DIGESTIBILITY': 0.006309148264984227, 'trait_name_IMPROVE_STOVE_DIGESTIBILITY': 0.0031545741324921135, 'trait_name_IMPROVE_TOLERANCE_TO_HUMID_CONDITIONS': 0.006309148264984227, 'trait_name_IMPROVE_TO_SEMI-LOOSE_PANICLE': 0.00946372239747634, 'trait_name_INSECT_RESISTANT': 0.0031545741324921135, 'trait_name_INSTABILITY': 0.0031545741324921135, 'trait_name_LARGE_GRAIN_SIZE': 0.0031545741324921135, 'trait_name_LARGE_HEAD_SIZE': 0.0031545741324921135, 'trait_name_LARGE_SEED_SIZE': 0.006309148264984227, 'trait_name_LATE_MATURITY': 0.012618296529968454, 'trait_name_LODGING_RESISTANT': 0.0031545741324921135, 'trait_name_LOWER_LEVEL_OF_TANNINS': 0.0031545741324921135, 'trait_name_LOW_PALATABILITY': 0.0031545741324921135, 'trait_name_LOW_STOVER_DIGESTIBILITY': 0.006309148264984227, 'trait_name_LOW_YIELD': 0.0031545741324921135, 'trait_name_MEDIUM_MATURING': 0.015772870662460567, 'trait_name_MEDIUM_MATURITY': 0.0031545741324921135, 'trait_name_MICRONUTRIENT_RICH': 0.0031545741324921135, 'trait_name_MOLD_RESISTANCE': 0.01892744479495268, 'trait_name_NARROW_ADAPTATION': 0.0031545741324921135, 'trait_name_OPEN_PANICLE': 0.015772870662460567, 'trait_name_POOR_STORABILITY': 0.0031545741324921135, 'trait_name_PRONE_TO_HEAT_STRESS': 0.0031545741324921135, 'trait_name_REDUCE_PLANT_HEIGHT': 0.0031545741324921135, 'trait_name_RESISTANCE_TO_ANTHRACNOSE': 0.00946372239747634, 'trait_name_RESISTANCE_TO_CHARCOAL_ROT': 0.006309148264984227, 'trait_name_RESISTANCE_TO_COVERED_KERNEL_SMUT': 0.006309148264984227, 'trait_name_RESISTANCE_TO_ELONGATED_SMUT': 0.006309148264984227, 'trait_name_RESISTANCE_TO_SOOTY_BLOTCH': 0.0031545741324921135, 'trait_name_RESISTANCE_TO_SORGHUM_MIDGE': 0.006309148264984227, 'trait_name_RESISTANCE_TO_STRIGA': 0.0031545741324921135, 'trait_name_RESISTANCE_TO_WATER_LOGGING': 0.0031545741324921135, 'trait_name_RESISTANT_TO_BIRD_DAMAGE': 0.0031545741324921135, 'trait_name_RESISTANT_TO_CHARCOAL_ROT': 0.0031545741324921135, 'trait_name_RESISTANT_TO_CHARCOAL_ROT.': 0.0031545741324921135, 'trait_name_RESISTANT_TO_CHARCOL_ROT': 0.0031545741324921135, 'trait_name_RESISTANT_TO_COVERED_KERNEL_SMUT': 0.006309148264984227, 'trait_name_RESISTANT_TO_GRAIN_MOLD': 0.012618296529968454, 'trait_name_RESISTANT_TO_LODGING': 0.00946372239747634, 'trait_name_RESISTANT_TO_STRIGA': 0.031545741324921134, 'trait_name_SHORT_STATURE': 0.0031545741324921135, 'trait_name_SMALL_GRAIN_SIZE': 0.0031545741324921135, 'trait_name_STAY_GREEN': 0.022082018927444796, 'trait_name_STRIGA_RESISTANCE': 0.006309148264984227, 'trait_name_STRIGA_TOLERANCE': 0.0031545741324921135, 'trait_name_SUSCEPTIBILITY_TO_WATER_LOGGING': 0.0031545741324921135, 'trait_name_SUSCEPTIBLE_TO_ANTHRACNOSE': 0.00946372239747634, 'trait_name_SUSCEPTIBLE_TO_BIRD_DAMAGE': 0.04416403785488959, 'trait_name_SUSCEPTIBLE_TO_CHARCOAL_ROT': 0.0031545741324921135, 'trait_name_SUSCEPTIBLE_TO_COVERED_KERNEL_SMUT': 0.006309148264984227, 'trait_name_SUSCEPTIBLE_TO_ELONGATED_SMUT': 0.0031545741324921135, 'trait_name_SUSCEPTIBLE_TO_ERGOT': 0.0031545741324921135, 'trait_name_SUSCEPTIBLE_TO_GRAIN_MOLD': 0.00946372239747634, 'trait_name_SUSCEPTIBLE_TO_MIDGE': 0.0031545741324921135, 'trait_name_SUSCEPTIBLE_TO_SEED_ABORTION': 0.0031545741324921135, 'trait_name_SUSCEPTIBLE_TO_SHOOT_FLY_DAMAGE_.': 0.0031545741324921135, 'trait_name_SUSCEPTIBLE_TO_SOOTY_BLOTCH': 0.0031545741324921135, 'trait_name_SUSCEPTIBLE_TO_SORGHUM_MIDGE': 0.012618296529968454, 'trait_name_SUSCEPTIBLE_TO_STRIGA': 0.012618296529968454, 'trait_name_SUSCEPTIBLE_TO_WATER_LOGGING': 0.00946372239747634, 'trait_name_TALL_PLANT_HEIGHT': 0.0031545741324921135, 'trait_name_TOLERANCE_TO_HEAT_STRESS': 0.0031545741324921135, 'trait_name_TOLERANCE_TO_HIGH_MOISTURE': 0.0031545741324921135, 'trait_name_TOLERANCE_TO_SORGHUM_MIDGE': 0.006309148264984227, 'trait_name_TOLERANT_TO_CHARCOAL_ROT': 0.0031545741324921135, 'trait_name_TOLERANT_TO_ELONGATED_SMUT': 0.0031545741324921135, 'trait_name_TOLERANT_TO_STRIGA': 0.0031545741324921135, 'trait_name_TOLERANT_TO_WATER_LOGGING': 0.0031545741324921135, 'trait_name_UNDESIRABLE_GRAIN_COLOUR': 0.00946372239747634, 'trait_name_UNDESIRABLE_RED_COLOR': 0.0031545741324921135, 'trait_name_WIDEN_ADAPTATION': 0.0031545741324921135, 'trait_name_WIDE_ADAPTATION': 0.00946372239747634, 'trait_type_Desired': 0.29652996845425866, 'trait_type_Negative': 0.22082018927444794, 'trait_type_Positive': 0.48264984227129337}

Key TPEs:
{'tpe_name_ARID': 1.0}

Key Conditions:
{'condition_broken clouds': 0.0, 'condition_clear sky': 0.0, 'condition_light rain': 0.0, 'condition_moderate rain': 0.0, 'condition_overcast clouds': 1.0, 'condition_scattered clouds': 0.0}

Key Months:
{'month_April': 0.08333333333333333, 'month_August': 0.08333333333333333, 'month_December': 0.08333333333333333, 'month_February': 0.08333333333333333, 'month_January': 0.08333333333333333, 'month_July': 0.08333333333333333, 'month_June': 0.08333333333333333, 'month_March': 0.08333333333333333, 'month_May': 0.08333333333333333, 'month_November': 0.08333333333333333, 'month_October': 0.08333333333333333, 'month_September': 0.08333333333333333}

Cluster 2 Analysis:

Numeric Summary:
{'lat': 0.47815219598739006, 'lon': -0.9929499594011298, 'temperature': 0.38500044358263524, 'humidity': 0.23382383736026852, 'rainfall': -0.5769603862754306}

Varieties:
['Mucuvea(2015)otela(2015)Yeipa1(2019)Kapaala(1996)Dorado(1996)AtokpleChi(2022)AdSARGHUM1(2022)AdSARGHUM2(2022)AdSARGHUM3(2022)Gadam(1994)KariMtama1(2000)Kamani(2019)SESO1(2011)NAROSORG1(2017)NAROSORG4(2017)SORVATO9(2019)ABM(2019)SOUBATIMI(2019)PépéKalé(2019)CS-54(1992)S-35(1965)Soubatimi(2015)Zouaye(2004)Tocole(2015)Maita-1(2015)Mapupulo(2015)Seso3(2018)SESO3(2011)IRAT-204(1994)IRAT204(1980)S-35(1986)Kolmonrouge(1993)Damougari(1998)Tiandougoucoura(2010)Sila(2016)Fadda(2010)Mota-Maradi(1994)K3R(1995)Tegemeo(1983)TARISOR1(2021)TARISOR2(2021)Macia(1999)Wahi(2002)Pablo(2011)NAROSORG2(2017)Macia(2012)AGRAC116(2016)ARAC216(2016)Seredo(1970)Grinkan(2007)']

Crops:
['sorghum']

Towns:
['KumasiLoméDoualaTamaleAccra']

Countries:
['GhanaTogoCameroon']

TPE Descriptions:
['Extremely dry areas with minimal rainfall, often less than 400 mm annually']

Stressors:
["['DROUGHT', 'HEAT', 'STRIGA', 'SALINITY']"]

Key Traits:

#### Filter Varieties by Environmental Conditions

In [29]:
def filter_by_country(country_of_interest):
    clusters_for_country = recommendation_table[
        recommendation_table['Countries'].apply(lambda x: country_of_interest in x)
    ]

    if clusters_for_country.empty:
        print(f"No clusters found for {country_of_interest}.")
    else:
        for index, row in clusters_for_country.iterrows():
            print(f"\nCluster {row['Cluster']} for {country_of_interest}:")
            print(f"Varieties: {row['Varieties']}")
            print(f"TPE Descriptions: {row['TPE Descriptions']}")
            print(f"Stressors: {row['Stressors']}")

# Example: Filter by Kenya
filter_by_country('Kenya')

No clusters found for Kenya.

In [ ]:
import ast

# Specify the country of interest
country_of_interest = 'Kenya'

# Find clusters that include the country
clusters_for_country = recommendation_table[
    recommendation_table['Countries'].apply(lambda x: country_of_interest in ast.literal_eval(x))
]

# Display the clusters and their varieties
if clusters_for_country.empty:
    print(f"No clusters found for {country_of_interest}.")
else:
    for index, row in clusters_for_country.iterrows():
        print(f"\nCluster {row['Cluster']} for {country_of_interest}:")
        print(f"Varieties: {ast.literal_eval(row['Varieties'])}")
        print(f"TPE Descriptions: {ast.literal_eval(row['TPE Descriptions'])}")
        print(f"Stressors: {ast.literal_eval(row['Stressors'])}")

In [22]:
import ast

# Display unique countries in the recommendation table
unique_countries = set()
for countries in recommendation_table['Countries']:
    unique_countries.update(ast.literal_eval(countries))

print("Unique countries in the dataset:", unique_countries)

Unique countries in the dataset: {'UgandaKenyaTanzania', 'GhanaTogoCameroon', 'Burkina FasoNiger', 'ChadSouth SudanCameroon', 'MozambiqueKenya'}